spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpassword
      database: interview-ranker
      port: 27017
      host: localhost

server:
  port: 9000