spring:
  profiles:
    active: "dev"
  main:
    banner-mode: off

  output:
    ansi:
      enabled: always

logging:
  file:
    name: logs/interview_ranker.log
    path: logs/
  level:
    com:
      ranker:
        interviewranker: debug