spring:
  main:
    banner-mode: "off"

  output:
    ansi:
      enabled: always

  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpassword
      database: interview-ranker
      port: 27017
      host: localhost

logging:
  file:
    name: logs/interview_ranker.log
    path: logs/
  level:
    com:
      ranker:
        interviewranker: debug

server:
  port: 9000